port: 4000
baseurl: /
url: http://localhost:4000
permalink: /blog/:title
markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
