port: 4000
baseurl: /
url: http://danhough.com
permalink: /blog/:title
markdown: redcarpet
exclude: ['favicon.sketch','scss', 'node_modules', 'new-blog-post.html', 'new-projects.html', 'new.html', 'package.json', 'gulpfile.js']
keep_files: ['img']
debug: true
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
