port: 4000
baseurl: /
url: http://danhough.com
permalink: /blog/:title
markdown: KramdownPygments
highlighter: pygments.rb
kramdown:
  input: GFM
exclude: ['favicon.sketch','scss', 'node_modules', 'new-blog-post.html', 'new-projects.html', 'new.html', 'package.json', 'gulpfile.js']
debug: true
gems:
  - jemoji
  - jekyll-redirect-from
  - pygments.rb
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
